### ISSUE TITLE
Grid fins placed in 4x symmetry have incorrect control direction

### ISSUE THREAD

**Issue by PyroSA** [LuxStice/SORRY#4]
The pitch seems to  be mirrored, inducing roll instead of pitch.
Yaw appears fine though.

Can't invert without individually placing the parts, so this makes for a very un-symmetric build.

**Comment by LuxStice** [comment]
I'll wait for the dev's implementation of gridfins to see what im doing wrong! Sorry to make you wait :s

**Comment by LuxStice** [comment]
Fixed in 0.4.0
